export * from './bpm.module';
export { FollowUpDetailsComponent } from './follow-up-details/follow-up-details.component';
export * from './interface/bpm.interface';
export { ProcessAttachmentsComponent } from './process-attachments/process-attachments.component';
export { ProcessDetailsSummaryComponent } from './process-details/process-details-summary/process-details-summary.component';
export { ProcessDetailsComponent } from './process-details/process-details.component';
export { ProcessListEmptyComponent } from './process-list-empty/process-list-empty.component';
export { ProcessListComponent } from './process-list/process-list.component';
export { FormatProcessDataService } from './services/formatProcessData.service';
export { TaskDetailsAttachmentsComponent } from './task-details/task-details-attachments/task-details-attachments.component';
export { TaskDetailsHistoryComponent } from './task-details/task-details-history/task-details-history.component';
export { TaskDetailsTaskComponent } from './task-details/task-details-task/task-details-task.component';
export { TaskDetailsComponent } from './task-details/task-details.component';
